### ISSUE TITLE
The FieldPointValue type is undefined

### ISSUE THREAD

**Issue by jiajiahub** [zer011b/fdtd3d#192]
file: perf-test-parallel-grid.cpp and ParallelGridDynamic.cpp

**Comment by zer011b** [comment]
Please share your build commands

**Comment by jiajiahub** [comment]
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=nvcc  -DCMAKE_C_COMPILER=nvcc  -DCUDA_ARCH_SM_TYPE=sm_80 -DPARALLEL_GRID=ON  -DCUDA_ENABLED=ON -DPRINT_MESSAGE=ON -DSOLVER_DIM_MODES=ALL -DVALUE_TYPE=d -DCOMPLEX_FIELD_VALUES=ON  ..

**Comment by jiajiahub** [comment]
Modified by CMakeLists: momessage (FATAL_ERROR "Debug CUDA builds with all dimension modes (ALL) are too heavy in terms of compilation time. Use specific dimension.")===>#message (FATAL_ERROR "Debug CUDA builds with all dimension modes (ALL) are too heavy in terms of compilation time. Use specific dimension.")
##### Comment this statement

**Comment by zer011b** [comment]
> The FieldPointValue type is undefined

Please share full build log.

> Comment this statement

This statement is there for a reason, because at least on older versions of nvcc compilation time was too long. You can use `-DSOLVER_DIM_MODES=DIM3`, for example, to build 3d mode only. 

Also, passing both `-DPARALLEL_GRID=ON` and `-DCUDA_ENABLED=ON` means that you plan to use mpi + cuda, but note that this mode might be slower than simply using cuda when all data fits in gpu memory. For more details on such launch see https://github.com/zer011b/fdtd3d/blob/master/Docs/Launch.md.

**Comment by jiajiahub** [comment]
Thank you for answering my question. I have a compilation problem.

**Comment by jiajiahub** [comment]
Thank you for answering my question.

**Comment by zer011b** [comment]
Feel free to reopen if you have any more question
